### ISSUE TITLE
filter by full or * path

### ISSUE THREAD

**Issue by kilianc** [jonschlinkert/filter-object#4]
```js
filter({
  removeMe: 'now',
  foo: {
    bar: {
      hello: 'hello',
      there: 'there'
    }
  },
  foosiz: 'to-remove'
}, ['foo.*'])
```

My expectation is that it should remove everything but `foo.*` but I get:

```js
{ foosiz: 'to-remove' }
```

**Comment by jonschlinkert** [comment]
definitely a bug. I just tested myself. However, the readme states that it should keep `foo.*`, not remove `foo.*`, but it's not even doing that correctly. ~~I'm thinking that it should do what you're saying.~~ I think it should work just like `Array.filter`.  @doowb what are your thoughts on this?

edit: here are some examples for discussion...

```js
console.log(filter({a: 'aaa', b: {c: {d: 'ddd', e: 'eee'}}, f: 'fff'}, ['!b']));
// I think this should return  { a: 'aaa', f: 'fff' }

console.log(filter({a: 'aaa', b: {c: {d: 'ddd', e: 'eee'}}, f: 'fff'}, ['b']));
// I think this should return  { b: { c: { d: 'ddd', e: 'eee' } } }
```

**Comment by doowb** [comment]
> However, the readme states that it should keep

Yeah, this library keeps the matching keys on an object (just like `Array.filter`). However, I don't think that glob pattern should be returning anything (in the current implementation) due to only checking against the first "level" of keys.

For nested keys, you can use [glob-object](https://github.com/jonschlinkert/glob-object) which uses the dot notation that you specified above.

**Comment by doowb** [comment]
I just tested some things and this looks like a bug that was in an older version of `micromatch` (which is being used in `filter-keys`). Updating `filter-keys` to the latest version of `micromatch` results in the correct results (an empty object in this case since the glob pattern doesn't match any of the keys).

**Comment by kilianc** [comment]
> However, the readme states that it should keep foo.*, not remove foo.*

That's exactly what I am after, edited my post for future readers :)
The way I am fixing this my end is flattening / unflattening to avoid dealing with nested data structures and recursion

**Comment by jonschlinkert** [comment]
I'm working on making some fixes to this now

**Comment by kilianc** [comment]
looks like what I want is `glob-object`, but the order of the arguments is reversed :D 

thanks for the fix
